branch-defaults:
  aws-deploy:
    environment: prod
environment-defaults:
  prod:
    branch: null
    repository: null
global:
  application_name: jumbosmash
  default_ec2_keyname: smash
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/(BETA) Python 3.7
    running on 64bit Amazon Linux 2/0.1.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
